Profile settings
harijar/geogame pull request #22
Opened 2023-12-24 21:14 UTC by harijar

2023-12-25 22:17 UTC, allmazz requested changes

2023-12-25 22:17 UTC, allmazz commented on internal/api/v1/services.go
> +	UpdateUser(ctx context.Context, user *users.User) error
Вот тут уже нужен UserService

2023-12-25 22:17 UTC, allmazz commented on internal/api/v1/update_profile_settings.go
> +	user.Public = request.Public
нужно добавить валидацию https://github.com/go-playground/validator

2023-12-25 22:17 UTC, allmazz commented on internal/service/statistics/statistics.go
> +	statistics.AverageGuesses = math.Round(statistics.AverageGuesses*100) / 100
а почему не делаешь это в запросе?

2023-12-25 22:17 UTC, allmazz commented on internal/repo/postgres/migrations/5_create_table_users.up.sql
> +    public BOOL
смысл миграций в том чтобы иметь возможность обновить имеющуюся бд, т.е поле надо добавлять в новой миграции

2023-12-25 22:17 UTC, allmazz commented on internal/api/v1/update_profile_settings.go
> +package v1
profile_setting_update

2023-12-25 22:17 UTC, allmazz commented on internal/api/v1/get_profile_settings.go
> +package v1
profile_settings_get

2023-12-25 22:17 UTC, allmazz commented on internal/api/v1/get_profile_settings.go
> +func (a *V1) getProfileSettings(c *gin.Context) {
у нас таблица users, почему он стал profile?

2024-01-01 13:10 UTC, allmazz requested changes

2024-01-01 13:10 UTC, allmazz commented on internal/api/v1/routes.go
> +	a.server.POST("/v1/profile/settings", a.updateProfileSettings)
метод должен называться profileSettingsUpdate аналогично другим

2024-01-01 13:10 UTC, allmazz commented on internal/service/auth/auth.go
> +	return a.usersRepo.Get(ctx, id)
и почему ты работаешь с репо? было бы логичнее использовать тут профайл сервис

2024-01-01 13:10 UTC, allmazz commented on internal/api/v1/auth.go
> +		user, err := a.authService.GetUser(c, int(request.ID))
сделай метод IsExists `select exists(select 1 from users where id = '...') as exists`

2024-01-07 13:55 UTC, allmazz requested changes

2024-01-07 13:55 UTC, allmazz commented on cmd/main/main.go
> +	profileService := usersService.New(usersRepo)
?)

2024-01-07 13:55 UTC, allmazz commented on internal/repo/postgres/migrations/6_alter_table_users.up.sql
> +    RENAME username TO telegram_username;
а где столбец с никнеймом?

2024-01-07 13:55 UTC, allmazz commented on frontend/js/auth.js
> +    alert('Logged in as ' + user.username)
так никнейм же, не?

2024-01-07 13:55 UTC, allmazz commented on internal/repo/postgres/migrations/6_alter_table_users.up.sql
> +    ADD COLUMN public bool;
зачем разделять на два статмента?

2024-01-07 13:55 UTC, allmazz commented on internal/api/v1/profile_settings.go
> +func (a *V1) checkAndUpdate(c context.Context, user *users.User) (int, string, error) {
валидацию в сервис

2024-01-09 16:15 UTC, harijar commented on internal/api/v1/profile.go
> +	c.JSON(http.StatusOK, response)
поздняк метаться

2024-01-09 16:39 UTC, allmazz requested changes

2024-01-09 16:39 UTC, allmazz commented on internal/service/users/users.go
> +	return updateErrors, nil
шляпа, ты же возвращаешь ошибку, костыль

2024-01-09 16:39 UTC, allmazz commented on internal/repo/repo.go
>  	Get(ctx context.Context, id int, columns ...string) (*users.User, error)
а как ты её будешь обрабатывать?

2024-01-17 17:37 UTC, merged